plugins { id 'com.android.application' }

apply from: "${rootProject.rootDir}/groovy/common-config.gradle"

android {
  namespace 'ua.navshlyah.app'

  defaultConfig {
    applicationId 'ua.navshlyah.app'
    versionCode 12
    versionName '1.2.0'
  }

  buildTypes {
    release {
      minifyEnabled false
      signingConfig signingConfigs.debug
    }
  }
}

dependencies {
  implementation project(':sdk')
}
